spring.application.name=notification
server.port=8180
# Jira config
jira.base-url=http://192.168.100.50:8032
jira.username=dunv
jira.password=Dunv123456@123

# Telegram bot
telegram.bot-token=8269533829:AAFF10Vi6ZiOtg7N-0ozYT-uvaDZRpu5uFU

telegram.chat-id=-5232128343

# Scheduler
scheduler.due-cron=0 0 8 * * ?
scheduler.done-last-day-cron=0 0 18 * * ?
app.config.jira=http://192.168.100.50:8032/browse/