spring.application.name=notification
server.port=8180
# Jira config
jira.base-url=http://14.224.201.179:8032
jira.username=dunv
jira.password=Dunv123456@123

# Telegram bot
telegram.bot-token=8269533829:AAFF10Vi6ZiOtg7N-0ozYT-uvaDZRpu5uFU
telegram.bot-username=JARVIS_GLOBAL_NOTI_BOT

telegram.chat-id=-5232128343

# Scheduler
#scheduler.due-cron=0 0 8 * * ?
scheduler.in-progress-cron=0 0 9 * * ?
scheduler.done-last-day-cron=0 0 18 * * ?
app.config.jira=http://14.224.201.179:8032/browse/
security.api-key= 123456789-secret
